[build-system]
requires = ["setuptools"]

[project]
name = "nightMARE"
version = "0.6.0"
dependencies = [
    "unicorn",
    "lief",
    "capstone",
    "construct",
    "yara-python",
    "requests",
    "smda",
]
requires-python = ">=3.10"
